# Generated by Django 5.0.3 on 2024-04-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
